version: '3'
services:
  web:
    build: .
    ports:
    - "5000:80"
    volumes:
    # - /Users/tonytonggg/Desktop/:/dst
    - ./data_science/unit_tests/sample_resumes/:/Resumes

# run this command: docker-compose up with this file in main directory
# rmb that using this, need to call files from the /dst pathing